Show project data
HadronCollider/sirius22-android pull request #17
Opened 2023-02-21 19:03 UTC by IlyaMatveev007

Сделано считывание данных определённого проекта.

2023-02-22 21:10 UTC, Jengle88 requested changes
Поправь замечания с галочками. Остальное по желанию

2023-02-22 21:10 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        data.id = 1
- [ ] У тебя же data не инициализирована, выстреливает kotlin.UninitializedPropertyAccessException

2023-02-22 21:10 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        allData.writeAllDataToFile()
- [ ] думаю сохранение в onPause будет достаточно

2023-02-22 21:10 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        allData.writeAllDataToFile()
- [ ] аналогично с onStop

2023-02-23 05:59 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/data/ProjectData.kt
>      @SerializedName("Quality") var quality: Byte,                   // качество модели, (можно изменять в процессе разработки)
А там в каких пределах для того класса качество надо давать?

2023-02-23 06:01 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        data.id = 1
Я знаю, это было исправлено в ветке select_image, могу здесь тоже исправить.

2023-02-23 06:11 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/data/ProjectData.kt
>      @SerializedName("Quality") var quality: Byte,                   // качество модели, (можно изменять в процессе разработки)
Хз. Я же не знаю, что ты под качеством подразумеваешь. Я к тому, что Byte больше с данными соотносится, а у нас просто маленькое число. Поэтому я и предложил на Short заменить

2023-02-23 06:13 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        data.id = 1
Как-то не очень, что ты баги из одной ветки исправляешь в других ветках. Лучше уж тогда исправлять баг здесь, а для другой ветки сделать rebase, если она основывается на этой ветке

2023-02-23 06:13 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/data/ProjectData.kt
>      @SerializedName("Quality") var quality: Byte,                   // качество модели, (можно изменять в процессе разработки)
Я поменял.

2023-02-23 06:16 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        data.id = 1
В этой ветке мне тоже исправить?

2023-02-23 06:18 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        data.id = 1
Да. И про галочки не забывай

2023-02-23 06:41 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        data.id = 1
Исправлено.

2023-02-23 12:53 UTC, Jengle88 requested changes

2023-02-23 12:53 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/data/ReadProjectData.kt
> +        allProjectsData.plus(information)
нужен add. Метод plus создаст тебе по месту новый список, который по твоей логике никуда не пойдёт

2023-02-23 12:53 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/data/ReadProjectData.kt
> +        allProjectsData.plus(ProjectData(id, name, quality, data))
тоже нужен add

2023-02-24 07:41 UTC, Jengle88 commented
@IlyaMatveev007 Возникает исключение при создании проекта, если до этого не было проектов, проблема в com/example/siriusproject/data/ReadProjectData.kt:13:
2023-02-24 10:39:03.644 13114-13114 AndroidRuntime          com.example.siriusproject            E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.siriusproject, PID: 13114
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.siriusproject/com.example.siriusproject.ProjectActivity}: kotlin.UninitializedPropertyAccessException: lateinit property allProjectsData has not been initialized
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                                                                                                    Caused by: kotlin.UninitializedPropertyAccessException: lateinit property allProjectsData has not been initialized
                                                                                                    	at com.example.siriusproject.data.ReadProjectData.getAllProjectsData(ReadProjectData.kt:13)
                                                                                                    	at com.example.siriusproject.ProjectActivity.onCreate(ProjectActivity.kt:32)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7136)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7127)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:193) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6669) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

2023-02-28 08:58 UTC, Jengle88 commented
@IlyaMatveev007 А где у тебя сохранение проекта (занесение его в список проектов) после его создания?

2023-03-01 16:38 UTC, Jengle88 commented
@IlyaMatveev007 ну что там с сохранением?

2023-03-01 21:23 UTC, Jengle88 requested changes

2023-03-01 21:23 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        if (arguments?.getString(R.string.type_type.toString()) == R.string.new_project_made.toString()) {
А что ты вообще здесь сравниваешь? R.string.new_project_made - это же Int

2023-03-01 21:23 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        if (arguments?.getString(R.string.type_type.toString()) == R.string.new_project_made.toString()) {
Также здесь выстреливает Exceptrion:
                                                                                                    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
                                                                                                    	at android.os.BaseBundle.getString(BaseBundle.java:1158)
                                                                                                    	at com.example.siriusproject.ProjectActivity.onCreate(ProjectActivity.kt:25)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7136)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7127)

2023-03-01 21:23 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/data/ReadProjectData.kt
> +            allProjectsData[allProjectsData.size - 1].id + 1
allProjectsData[allProjectsData.size - 1] - на будущее, можно заменить на allProjectsData.last(). Но вообще не критично

2023-03-01 21:23 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +                Toast.makeText(this, "Error! Can't find the project", Toast.LENGTH_SHORT).show()
При попытке добавить новый проект в пустой список - попадаю сюда. Проект не создаётся

2023-03-02 15:03 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        if (arguments?.getString(R.string.type_type.toString()) == R.string.new_project_made.toString()) {
А у меня нету.

2023-03-02 15:04 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        if (arguments?.getString(R.string.type_type.toString()) == R.string.new_project_made.toString()) {
А как мне там получить String который я написал в файле strings.xml?

2023-03-02 15:16 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        if (arguments?.getString(R.string.type_type.toString()) == R.string.new_project_made.toString()) {
<твой контекст>.getString(R.string.<твоя строка>)

2023-03-02 15:37 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        if (arguments?.getString(R.string.type_type.toString()) == R.string.new_project_made.toString()) {
Нету.

2023-03-02 15:54 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        if (arguments?.getString(R.string.type_type.toString()) == R.string.new_project_made.toString()) {
значит на созвоне покажу

2023-03-02 18:14 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/data/ReadProjectData.kt
> +            allProjectsData[allProjectsData.size - 1].id + 1
Исправлено.

2023-03-02 18:18 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        if (arguments?.getString(R.string.type_type.toString()) == R.string.new_project_made.toString()) {
Исправлено.

2023-03-02 18:44 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +                Toast.makeText(this, "Error! Can't find the project", Toast.LENGTH_SHORT).show()
@IlyaMatveev007 я так и не нашёл, куда сохраняются данные о проекте. После создания проекта и перезапуска приложения - список всё равно пустой

2023-03-02 19:56 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +                Toast.makeText(this, "Error! Can't find the project", Toast.LENGTH_SHORT).show()
Это из-за того, что данные сохраняются только в onPause, я добавил сохранение в onDestroy и теперь нормально работает.

2023-03-03 13:34 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +                Toast.makeText(this, "Error! Can't find the project", Toast.LENGTH_SHORT).show()
onDestroy - не самое лучшее решение, ибо он не всегда может вызываться. Поэтому и сохранение у тебя может быть не всегда

2023-03-03 14:44 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +                Toast.makeText(this, "Error! Can't find the project", Toast.LENGTH_SHORT).show()
А тогда ещё в onStop сделать сохранение?

2023-03-03 14:47 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +                Toast.makeText(this, "Error! Can't find the project", Toast.LENGTH_SHORT).show()
А что за проблема с onPause? Почему там не сохраняется?

2023-03-04 18:56 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +                Toast.makeText(this, "Error! Can't find the project", Toast.LENGTH_SHORT).show()
Если сделать только в onPause и прерывать работу приложения через ide, то эта функция скорее всего не вызывается и данные не сохраняются.

2023-03-05 17:16 UTC, Jengle88 commented
@IlyaMatveev007 Я увидел, что данные сохраняются, но они не отображаются при повторном запуске приложения. Также у тебя вместо названия проекта идёт null. Всё это считается ожидаемым поведением?

2023-03-08 17:16 UTC, Jengle88 commented
@IlyaMatveev007 Пинг к сообщению выше

2023-03-08 18:14 UTC, merged