Interface1
HadronCollider/sirius22-android pull request #18
Opened 2023-03-09 15:22 UTC by IlyaMatveev007

В данной ветке исправлен способ доступа к элементам интерфейса, сделан список начальных проектов.

2023-03-10 16:11 UTC, Jengle88 requested changes
- [x] После создания проект переход назад производится в активити создания проекта - не ок

- [x] Всё равно после создания проектов их имя null. 
![Снимок экрана от 2023-03-10 19-10-16](https://user-images.githubusercontent.com/45243533/224366129-6caa86c0-18ff-462e-a5a5-d170cd727cf6.png)

2023-03-10 16:38 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/data/ProjectActionListener.kt
> +interface ProjectActionListener {
Это нужно, для того, чтобы не передавать в адаптер активити.

2023-03-10 16:43 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/data/ProjectActionListener.kt
> +interface ProjectActionListener {
вопрос о том, зачем тебе интерфейс для одного метода?

2023-03-10 17:02 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/data/ProjectActionListener.kt
> +interface ProjectActionListener {
Там можно ещё сделать удаление проектов. Это нужно?

2023-03-10 17:06 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/data/ProjectActionListener.kt
> +interface ProjectActionListener {
И надо-ли делать сортировку по дате изменения проекта? Сейчас они расположены по id и самые новые будут в конце.

2023-03-10 18:09 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/data/ProjectActionListener.kt
> +interface ProjectActionListener {
Можно сделать удаление проектов. Тогда интерфейс будет уже оправдан. Насчёт сортировки - не нужно, пусть будет по ID

2023-03-10 19:28 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/data/ProjectActionListener.kt
> +interface ProjectActionListener {
Хорошо.

2023-03-15 16:00 UTC, Jengle88 approved these changes

2023-03-15 16:00 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/New_project.kt
> +            startActivityForResult(projectActivity, 1)
Лучше не ставить коды как просто числа. Лучше использовать именованную как константу (возможно даже статическую), например val SUPER_CODE = 1. Иначе потом не вспомнишь, что такое код 1, 2, 3 и тп

2023-03-16 15:01 UTC, merged