Фильтрация файлов в папке проекта.
HadronCollider/sirius22-android pull request #27
Opened 2023-04-25 19:12 UTC by IlyaMatveev007

2023-04-26 07:25 UTC, Jengle88 requested changes

2023-04-26 07:25 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        for (i in images) {
а что мешает сделать это сразу в walk().forEach ?

2023-04-26 07:25 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +            if (i.path.toString().endsWith(".jpeg")) {
- [ ] Что будет, если пользователь добавит .png изображение из памяти устройства? 
- [ ] Всегда ли у JPEG изображений расширение .jpeg? есть же .jpg

2023-04-28 16:07 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +        for (i in images) {
Исправлено.

2023-04-30 19:01 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +            if (!firstPosition) {
Убрано.

2023-04-30 19:05 UTC, IlyaMatveev007 commented
Если запустить камеру приложения, то она сохраняет свои изображения в папку, которая находится в директории проекта. И при считывании всех изображений они тоже считываются, надо сделать проверку, что изображения находятся только в корневой папке проекта.

2023-05-04 18:03 UTC, merged

2023-05-04 18:14 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +            path.substring(dirOfThisProject.length - 1, path.length).forEachIndexed { index, it ->
Так ведь индексация с 0.

2023-05-04 18:18 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +            path.substring(dirOfThisProject.length - 1, path.length).forEachIndexed { index, it ->
а причём здесь индексация?

2023-05-04 18:26 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +            path.substring(dirOfThisProject.length - 1, path.length).forEachIndexed { index, it ->
А ну в принципе можно не брать этот элемент.