Добавлен Ripple Effect для кнопки фотографирования.
HadronCollider/sirius22-android pull request #35
Opened 2023-05-05 19:29 UTC by IlyaMatveev007

2023-05-07 12:16 UTC, Jengle88 requested changes
- RippleEffect - ОК
- Настройки качества - ОК
- Иконка "Папка" - ОК
- Отцентровка текста - ОК
- Кнопки настроек - не увидел разницы, всё также перекрывается

2023-05-07 16:32 UTC, IlyaMatveev007 commented
Довольно сложно будет сделать кнопки, у меня просто этого ни на телефоне, ни на эмуляторе нету.

2023-05-07 16:36 UTC, Jengle88 commented
Как я и говорил, попробуй их объединить через LinearLayout, а не просто выставить выравнивание

2023-05-07 18:20 UTC, Jengle88 commented
Ну почти
![изображение](https://user-images.githubusercontent.com/45243533/236695376-44dd6447-d718-440a-afbd-9d9316cedb1a.png)
Тебе нужно только 2 элемента обернуть в LinearLayout, а сам конец этот layout выровнять по концу родителя

2023-05-07 18:21 UTC, Jengle88 commented
И убери такую зависимость от dp
`            android:layout_width="200dp"`
Думаю во многом из-за этого у тебя проблемы возникают

2023-05-10 18:37 UTC, Jengle88 commented
@IlyaMatveev007 Так, у меня тут совсем из головы вылетело, что для Toolbar нужно добавлять кнопки не стандартным способом. Думаю поэтому у нас и не получается их расставить. Прочти [здесь](https://m2.material.io/components/app-bars-top/android#regular-top-app-bar) про использование Toolbar в приложения. Если вкратце - вместо обычного layout нужно делать ресурс файл типа menu и там прописывать элементы, которые тебе нужны. На сайте есть пример - @menu/top_app_bar.xml, что-то похожее тебе нужно сделать и вставить в твой Toolbar

2023-05-15 18:53 UTC, Jengle88 approved these changes

2023-05-15 18:53 UTC, Jengle88 commented on app/src/main/res/layout/activity_new_project.xml
> +        android:layout_marginTop="-455dp"
Почему оно отрицательное?

2023-05-19 18:49 UTC, IlyaMatveev007 commented on app/src/main/res/layout/activity_new_project.xml
> +        android:layout_marginTop="-455dp"
Исправлено.

2023-05-19 18:57 UTC, merged