Ускорение добавления изображений в проект, и оптимизация списка.
HadronCollider/sirius22-android pull request #36
Opened 2023-05-07 12:45 UTC by IlyaMatveev007

…анилища телефона. Сделано удаление как нормального изображения, так и маленького. Сжатые изображения сохраняются в папке img файлов проекта.

2023-05-10 18:44 UTC, Jengle88 commented
Кажется, у тебя при отображении фулл картинки загружается сжатая версия
![изображение](https://github.com/HadronCollider/sirius22-android/assets/45243533/5651dbbc-d273-4acb-87ad-b8fb4f2000ba)

2023-05-11 14:33 UTC, Jengle88 requested changes
При попытке удаления снимка появляется сообщение "can`t find the image". Сам файл  удаляется, но при этом в списке остаётся элемент, который исчезает при переходе на другую активность

2023-05-11 14:33 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +    companion object {
Убрать

2023-05-11 19:40 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/Utils.kt
> +class Utils {
Сделано.

2023-05-11 19:41 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +    companion object {
Убрано.

2023-05-15 19:02 UTC, Jengle88 approved these changes
- [x] Удалить сообщение "deleted succesfully" об успешном удалении изображения

2023-05-16 17:14 UTC, merged