Сделан переход на активити построения модели.
HadronCollider/sirius22-android pull request #37
Opened 2023-05-08 16:02 UTC by IlyaMatveev007

В данной ветке загружаются изображения только из формата jpg, загрузка изображений из других форматов сделана в другой ветке и сейчас находится в main

2023-05-10 18:50 UTC, Jengle88 approved these changes

2023-05-10 18:50 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/boofcv/DemoCamera2Activity.java
> +        return true; //cameraId.equals(app.preference.cameraId);
- [ ] убрать комментарий

2023-05-10 18:50 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/boofcv/MultiViewStereoActivity.java
> +//		if(Objects.equals(Environment.getExternalStorageState(), Enviroent.MEDIA_MOUNTED)) {
- [ ] убрать комментарии, если они не нужны

2023-05-10 18:50 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/boofcv/MultiViewStereoActivity.java
> +
- [ ] Убрать лишний дифф

2023-05-10 18:50 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
>              // TODO: Добавить проверку на доступность камеры
Потом нужно будет пройтись по коду и проверить все TODO, что были оставлены

2023-05-15 18:56 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
>              // TODO: Добавить проверку на доступность камеры
Исправлено

2023-05-15 19:53 UTC, Jengle88 requested changes

2023-05-15 19:53 UTC, Jengle88 commented on app/build.gradle
> +        sourceCompatibility JavaVersion.VERSION_11
В честь чего поднял?

2023-05-15 19:53 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
>              // TODO: Добавить проверку на доступность камеры
Комментарий тоже нужно убрать :)

2023-05-15 19:53 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +                finish()
Зачем закрываешь текущую активность?

2023-05-15 19:55 UTC, Jengle88 commented
Также нужно исправить мои комментарии к ПР выше

2023-05-16 04:39 UTC, IlyaMatveev007 commented on app/build.gradle
> +        sourceCompatibility JavaVersion.VERSION_11
Я для ускорения билда, по крайней мере так говорила android stydio, также я хотел сделать проверку на cleancode через консоль, а как оказалось там надо в системе поменять версию java. И можно вернуть обратно.

2023-05-17 20:49 UTC, Jengle88 approved these changes

2023-05-17 20:49 UTC, Jengle88 commented on app/build.gradle
> +        sourceCompatibility JavaVersion.VERSION_11
А по итогу - оно нужно или нет?

2023-05-17 20:49 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/CameraActivity.kt
> +        if (Utils.allPermissionsGranted(baseContext)) {
baseContext замени на this, чтобы брать контекст активности

2023-05-17 20:49 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/CameraActivity.kt
> +            if (Utils.allPermissionsGranted(baseContext)) {
baseContext -> this

2023-05-17 20:49 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +            if (Utils.allPermissionsGranted(baseContext)) {
baseContext -> this

2023-05-17 20:49 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/ProjectActivity.kt
> +            if (Utils.allPermissionsGranted(baseContext)) {
baseContext -> this

2023-05-17 20:49 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/Utils.kt
> +    fun allPermissionsGranted(baseContext: Context) = REQUIRED_PERMISSIONS.all {
по-хорошему, замени название переменной baseContext на context

2023-05-18 16:57 UTC, IlyaMatveev007 commented on app/build.gradle
> +        sourceCompatibility JavaVersion.VERSION_11
По итогу не нужно.

2023-05-19 18:21 UTC, merged