Сделан экран камеры, реализованы классы для работы с камерой.
HadronCollider/sirius22-android pull request #7
Opened 2023-01-14 17:51 UTC by IlyaMatveev007

Сделан activity камеры

2023-01-15 08:56 UTC, Jengle88 requested changes

2023-01-15 08:56 UTC, Jengle88 commented on app/src/main/AndroidManifest.xml
> +        <activity
Для начала пофикси конфликты, чтобы можно было мержить

2023-01-17 11:15 UTC, Jengle88 requested changes
Тем не менее, конфликт остался. Нужно его пофиксить. Знаешь как?

2023-01-21 17:07 UTC, Jengle88 requested changes

2023-01-21 17:07 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/Camera.kt
> +private fun getCameraInstance(): Camera? {
Зачем вынес из класса Camera?

2023-01-21 17:07 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/CameraPreview.kt
> +    private var mCamera: Camera,
val

2023-01-21 17:07 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/Camera.kt
> +class Camera : Activity() {
А как перейти к этой активити?

2023-01-21 17:07 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/CameraPreview.kt
> +    private val TAG = "Camera"
CameraPreview

2023-01-22 12:49 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/Camera.kt
> +class Camera : Activity() {
Для этого нужны изменения из ветки interface.

2023-01-22 17:22 UTC, Jengle88 commented on app/src/main/java/com/example/siriusproject/Camera.kt
> +class Camera : Activity() {
Т.е чтобы перейти к камере, нужен этот PR для активити и другой PR для перехода к ней?

2023-01-22 17:25 UTC, IlyaMatveev007 commented on app/src/main/java/com/example/siriusproject/Camera.kt
> +class Camera : Activity() {
Нужны изменения из ветки interface, и надо сделать listner для кнопки.

2023-01-22 17:28 UTC, merged